version: "3.8"

name: searcher

services:
  kafka:
    extends:
      file: ./docker/docker-compose-kafka.yml
      service: kafka
  
  kafka-ui:
    extends:
      file: ./docker/docker-compose-kafka.yml
      service: kafka-ui

  pgvector:
    extends:
      file: ./docker/docker-compose-pgvector.yml
      service: pgvector

  qdrant:
    extends:
      file: ./docker/docker-compose-qdrant.yml
      service: qdrant

configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  kafka_data:
  pgvector_data:
  qdrant_data:
